### ISSUE TITLE
SeekingLimitStream::seek is not compatible with psr/http-message 1.1

### ISSUE THREAD

**Issue by caricare2** [zbateson/stream-decorators#16] opened 2023-05-02 18:46 UTC
While using zbateson/mail-mime-parser and I ran into an issue where zbateson/stream-decorators version 1.2.0 uses a declaration for SeekingLimitStream::seek that is not compatible with psr/http-message 1.1. It looks like the change in declaration is made in psr/http-message 2.0, but I am not sure this is compatible with some of my other libraries so I didn't want to upgrade. 

I was able to get it working by downgrading to 1.1.0, but if psr/http-message 2.0 is required for zbateson/stream-decorators 1.2.0 then this requirement should be listed for composer.

**Comment by odinns** [comment] 2023-05-26 09:03
I just ran into this issue when adding spatie/laravel-ray and had to downgrade to 1.1.0 to avoid it, so a fix of some kind would be much appreciated 👍 

Took me a while to find that this was the cause 😢

**Comment by zbateson** [comment] 2023-05-30 23:01
Fixed in 1.2.1

**Closed by zbateson** 2023-05-30 23:01 UTC

**Comment by odinns** [comment] 2023-05-31 20:15
Thanks! 😊
